version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  reporting-hub-bop-shell:
    container_name: reporting-hub-bop-shell
    image: mojaloop/reporting-hub-bop-shell
    build:
      context: .
      cache_from:
        - mojaloop/reporting-hub-bop-shell
      args:
        - PUBLIC_PATH=http://localhost:3010/
        - REACT_APP_API_BASE_URL=/api
        - REACT_APP_AUTH_ENABLED=true
        - REACT_APP_MOCK_API=true
        - REMOTE_1_URL=http://localhost:3012
        - REMOTE_2_URL=http://localhost:3013
    ports:
      - "3010:3010"
    networks:
      - mojaloop-net
    healthcheck:
      test: wget -q http://172.17.0.1:3010 -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
